version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - ENVIRONMENT=dev
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=true
      - MONGO_DETAILS=mongodb://db:27017
    command:
      ['start', '8000']

  db:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
      - data:/bitnami/mongodb

volumes:
  data:
