name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: bitnami/mongodb:latest
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v1
      
      - name: install python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: install requirements
        run: pip3 install --no-cache-dir -r requirements.prod.txt -r requirements.dev.txt
        
      - name: run checks and tests
        run: ./docker-entrypoint.sh tests
        env:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          MONGO_DETAILS: "mongodb://127.0.0.1:27017"
