name: CI

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: bitnami/mongodb:latest
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v1

      - name: docker-ci-action
        uses: ./
        env:
          MONGO_DETAILS: "mongodb://mongodb:27017"
